"""Generate the two extra STEP fixtures needed by issue 004.

Produces:
  - tests/fixtures/step/self_hex_nut.step
  - tests/fixtures/step/self_filleted_cylinder.step

And writes sibling .expected.json files with curated ground truth.
Re-runnable: overwrites existing outputs deterministically.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
from pathlib import Path

import cadquery as cq

ROOT = Path(__file__).resolve().parent.parent
FIX_DIR = ROOT / "tests" / "fixtures" / "step"
FIX_DIR.mkdir(parents=True, exist_ok=True)


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    h.update(p.read_bytes())
    return h.hexdigest()


def write_expected(step_path: Path, payload: dict) -> None:
    out = step_path.with_suffix("").with_suffix(".expected.json")
    out_name = step_path.name.replace(".step", ".expected.json")
    out = step_path.parent / out_name
    payload = dict(payload)
    payload["fixture"] = step_path.name
    payload["file"] = {
        "sizeBytes": step_path.stat().st_size,
        "sha256": sha256(step_path),
    }
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


# ── 1) Hex nut: across-flats 17 mm, thickness 8 mm, M10 through-hole ─────────
AF = 17.0
THICK = 8.0
BORE = 10.0
inradius = AF / 2.0  # apothem
circumradius = inradius / math.cos(math.pi / 6.0)  # vertex distance

hex_nut = (
    cq.Workplane("XY")
    .polygon(6, circumradius * 2.0)  # cadquery's polygon takes circumscribed diameter
    .extrude(THICK)
    .faces(">Z")
    .workplane()
    .hole(BORE)
)
hex_nut_volume = math.sqrt(3) / 2.0 * (AF ** 2) * THICK - math.pi * (BORE / 2.0) ** 2 * THICK
hex_path = FIX_DIR / "self_hex_nut.step"
cq.exporters.export(hex_nut, str(hex_path), exportType="STEP")
write_expected(
    hex_path,
    {
        "purpose": "Self-authored hex nut: 17 mm across-flats, 8 mm thick, M10 through-bore. Second hex fixture required by shapeAnalysis golden tests.",
        "categories": ["hex bar stock", "hex with through-hole", "fastener"],
        "source": {
            "kind": "self-authored-generated",
            "name": "CadQuery generated by Claude for issue 004",
            "url": "generated during issue 004 fixture creation",
            "license": "project-internal",
        },
        "expected": {
            "unit": "millimeter",
            "meshCount": 1,
            "duplicateGroupCount": 1,
            "duplicateGroupSizes": [1],
            "dominantShape": "hex",
            "shapeKind": "hex",
            "shapeDims": {"afMm": AF, "lengthMm": THICK},
            "holeCount": 1,
            "boundingBoxMm": {
                "x": round(circumradius * 2.0, 6),
                "y": round(AF, 6),
                "z": THICK,
            },
            "volumeMm3": round(hex_nut_volume, 3),
        },
        "groundTruth": {
            "method": "CadQuery source dimensions; baseline values derived directly from constructive parameters.",
            "reviewedBy": "Claude",
            "reviewDate": "2026-05-21",
        },
    },
)

# ── 1b) Hex standoff: AF=20 mm, thickness 25 mm, 8 mm through-bore ───────────
AF2 = 20.0
THICK2 = 25.0
BORE2 = 8.0
inradius2 = AF2 / 2.0
circumradius2 = inradius2 / math.cos(math.pi / 6.0)

hex_standoff = (
    cq.Workplane("XY")
    .polygon(6, circumradius2 * 2.0)
    .extrude(THICK2)
    .faces(">Z")
    .workplane()
    .hole(BORE2)
)
hex_standoff_volume = math.sqrt(3) / 2.0 * (AF2 ** 2) * THICK2 - math.pi * (BORE2 / 2.0) ** 2 * THICK2
standoff_path = FIX_DIR / "self_hex_standoff.step"
cq.exporters.export(hex_standoff, str(standoff_path), exportType="STEP")
write_expected(
    standoff_path,
    {
        "purpose": "Self-authored hex standoff: 20 mm across-flats, 25 mm thick, 8 mm through-bore. Third hex fixture for shapeAnalysis coverage with distinct proportions.",
        "categories": ["hex bar stock", "hex with through-hole", "fastener"],
        "source": {
            "kind": "self-authored-generated",
            "name": "CadQuery generated by Claude for issue 004",
            "url": "generated during issue 004 fixture creation",
            "license": "project-internal",
        },
        "expected": {
            "unit": "millimeter",
            "meshCount": 1,
            "duplicateGroupCount": 1,
            "duplicateGroupSizes": [1],
            "dominantShape": "hex",
            "shapeKind": "hex",
            "shapeDims": {"afMm": AF2, "lengthMm": THICK2},
            "holeCount": 1,
            "boundingBoxMm": {
                "x": round(circumradius2 * 2.0, 6),
                "y": round(AF2, 6),
                "z": THICK2,
            },
            "volumeMm3": round(hex_standoff_volume, 3),
        },
        "groundTruth": {
            "method": "CadQuery source dimensions; baseline values derived directly from constructive parameters.",
            "reviewedBy": "Claude",
            "reviewDate": "2026-05-21",
        },
    },
)

# ── 2) Filleted cylinder: D=30, L=50, both rim edges 3 mm fillet ─────────────
DIA = 30.0
LEN = 50.0
FILLET = 3.0

filleted_cyl = (
    cq.Workplane("XY")
    .circle(DIA / 2.0)
    .extrude(LEN)
    .edges("%CIRCLE")
    .fillet(FILLET)
)
# Approximate volume: full cylinder minus 8 corner-bite approximations is overkill;
# the side-wall classifier doesn't care about exact volume — we record the nominal
# cylinder volume as a soft baseline.
filleted_cyl_volume_nominal = math.pi * (DIA / 2.0) ** 2 * LEN
fcyl_path = FIX_DIR / "self_filleted_cylinder.step"
cq.exporters.export(filleted_cyl, str(fcyl_path), exportType="STEP")
write_expected(
    fcyl_path,
    {
        "purpose": "Self-authored cylinder D30 x L50 with 3 mm fillets on both rim edges. Acceptance fixture proving filleted cylinders still classify as cylinder, not box.",
        "categories": ["round shaft", "filleted edges", "classification edge case"],
        "source": {
            "kind": "self-authored-generated",
            "name": "CadQuery generated by Claude for issue 004",
            "url": "generated during issue 004 fixture creation",
            "license": "project-internal",
        },
        "expected": {
            "unit": "millimeter",
            "meshCount": 1,
            "duplicateGroupCount": 1,
            "duplicateGroupSizes": [1],
            "dominantShape": "cylinder",
            "shapeKind": "cylinder",
            "shapeDims": {
                "outerDiaMm": DIA,
                "innerDiaMm": None,
                "lengthMm": LEN,
            },
            "holeCount": 0,
            "boundingBoxMm": {"x": DIA, "y": DIA, "z": LEN},
            "volumeMm3Nominal": round(filleted_cyl_volume_nominal, 3),
        },
        "groundTruth": {
            "method": "CadQuery source dimensions. Volume recorded as nominal-cylinder value; fillet bite is ignored because shapeAnalysis classifies from side-wall geometry, not volume.",
            "reviewedBy": "Claude",
            "reviewDate": "2026-05-21",
        },
    },
)

for p in (hex_path, standoff_path, fcyl_path):
    print(f"wrote {p.relative_to(ROOT)}  ({p.stat().st_size} bytes)")
